### ISSUE TITLE
为什么要限制一些快递呢？

### ISSUE THREAD

**Issue by GStepOne** [inbjo/express#3]
$allow_shipping_code = ['youzhengguonei', 'youzhengguoji', 'ems', 'emsguoji', 'emsinten', 'bjemstckj', 'shunfeng', 'shentong', 'yuantong', 'zhongtong', 'huitongkuaidi', ......]
这里面没有极兔jtexpress 没有丰网，是因为时间的原因么

**Comment by inbjo** [comment]
> $allow_shipping_code = ['youzhengguonei', 'youzhengguoji', 'ems', 'emsguoji', 'emsinten', 'bjemstckj', 'shunfeng', 'shentong', 'yuantong', 'zhongtong', 'huitongkuaidi', ......] 这里面没有极兔jtexpress 没有丰网，是因为时间的原因么

是的，开发的时候还没极兔和丰网，欢迎提交PR。

**Comment by GStepOne** [comment]
OK

**Comment by inbjo** [comment]
已合并PR https://github.com/inbjo/express/pull/5  感谢
